<?php
$title = 'Add New Car';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<section>
<?php
$form->setAttribute('action', $this->url('car', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('carPicture'));
echo $this->formRow($form->get('carPic2'));
echo $this->formRow($form->get('carPic3'));
echo $this->formRow($form->get('carPic4'));
echo $this->formRow($form->get('carPic5'));
echo $this->formRow($form->get('carPic6'));
echo $this->formRow($form->get('carPic7'));
echo $this->formRow($form->get('carPic8'));
echo $this->formRow($form->get('carPic9'));
echo $this->formRow($form->get('carPic10'));

echo $this->formRow($form->get('make'));
echo $this->formRow($form->get('model'));
echo $this->formRow($form->get('modelYear'));
?>
</section>
<section>
<?php
echo $this->formRow($form->get('engineSize'));
echo $this->formRow($form->get('brochureSize'));
echo $this->formRow($form->get('topSpeed'));
echo $this->formRow($form->get('noughtToSixty'));
echo $this->formRow($form->get('enginePowerBHP'));
echo $this->formRow($form->get('drivetrain'));
?>
</section>
<section>
    
<?php
echo $this->formRow($form->get('economyUrban'));
echo $this->formRow($form->get('economyExtraUrban'));
echo $this->formRow($form->get('economyCombined'));
echo $this->formRow($form->get('emissions'));
echo $this->formRow($form->get('annualTax'));
?>
</section>
<section>
<?php
echo $this->formRow($form->get('mileage'));
echo $this->formRow($form->get('bodyType'));
echo $this->formRow($form->get('noOfDoors'));
echo $this->formRow($form->get('noOfSeats'));
echo $this->formRow($form->get('transmission'));
echo $this->formRow($form->get('fuelType'));
echo $this->formRow($form->get('colour'));
echo $this->formRow($form->get('price'));
?>
</section>
<section>
<?php
echo $this->formRow($form->get('details'));
?>
</section>
<section>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</section>