<?php
$title = 'My Cars';
$this->headTitle($title);
?>
<section>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>Real Autos is where I list a bunch of cars in the Zend 2 framework.</p>
    <br/>
    <p><strong>Contact us for any enquiries you may have!</strong></p> 
</section>
<section>
    <?php foreach ($cars as $car) : ?>
        <div class="container-fluid">    
            <div class="row index-car-block"> 
                <div class="col-md-4 block-center index-car-img-block">
                    <?php if ($car->carPicture == null) : ?>
                        <img class="index-car-photo" src='<?php echo $this->basePath() ?>/img/pictureNotUploaded.bmp' alt='No Picture'>
                    <?php else: ?>
                        <img class="index-car-photo" src='<?php echo $this->basePath() ?>/img/<?php echo $car->carPicture; ?>.jpg' alt='No Picture'>
                    <?php endif; ?>
                </div>
                <div class="block col-md-5 index-car-desc-block">
                    <h2><u><?php echo $this->escapeHtml($car->make); ?></u></h2>  
                    <h5><?php echo $this->escapeHtml($car->model); ?></h5>
                    <br/>
                    <div class="row">
                        <div class="col-5 index-car-detail">
                            <img class="indexLogos" src="<?php echo $this->basePath() ?>/img/mileageLogo.bmp" alt="no picture"/> 
                            &nbsp;<?php echo $this->escapeHtml($car->mileage); ?>
                        </div>
                        <div class="col-5 index-car-detail">
                            <img class="indexLogos" src="<?php echo $this->basePath() ?>/img/transmissionLogo.bmp" alt="no picture"/>                                                                           
                            &nbsp;<?php echo $this->escapeHtml($car->transmission); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5 index-car-detail">
                            <img class="indexLogos" src="<?php echo $this->basePath() ?>/img/colourLogo.bmp" alt="no picture"/>                                  
                            &nbsp;<?php echo $this->escapeHtml($car->colour); ?>            
                        </div>
                        <div class="col-5 index-car-detail">
                            <img class="indexLogos" src="<?php echo $this->basePath() ?>/img/bodyTypeLogo.bmp" alt="no picture"/>
                            &nbsp;<?php echo $this->escapeHtml($car->bodyType); ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5 index-car-detail">
                            <img class="indexLogos" src="<?php echo $this->basePath() ?>/img/fuelTypeLogo.bmp" alt="no picture"/>                         
                            &nbsp;<?php echo $this->escapeHtml($car->fuelType); ?>
                        </div>
                    </div>
                </div>
                <div class="block col-md-3 block-center index-car-butt-block">
                    <h4 class="price-tag"><strong><u>&pound;<?php echo $this->escapeHtml($car->price); ?></u></strong></h4>
                    <div class="flex-holder">
                        <a class="btn btn-primary btn-block btn-lg hidden-print" id="index-car-button" href="<?php echo $this->url('car',
                        array('action'=>'viewcar', 'id' => $car->id));?>" role="button">Full Details</a>
                    </div>
                    <br/>
                    <p><a href="<?php echo $this->url('car',
                     array('action'=>'edit', 'id' => $car->id));?>">Edit</a> - 
                     <a href="<?php echo $this->url('car',
                     array('action'=>'delete', 'id' => $car->id));?>">Delete</a></p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</section>
<script src="<?php echo $this->basePath() ?>/js/buttonHandler.js" type="text/javascript"></script>